package com.example.editor.service;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.example.editor.model.CompletionRequest;
import com.example.editor.model.CompletionResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class GeminiService {

    @Value("${gemini.api.key}")
    private String apiKey;

    public CompletionResponse getCompletion(CompletionRequest req) {
        try {
            // Build the prompt text
            String prompt = String.format("""
                You are a helpful code assistant.
                Given the following JavaScript/TypeScript code context:
                %s
                Cursor position: %d
                Return JSON: {"completions": [{"label":"...","insert":"..."}]}
                """, req.getCode(), req.getCursor());

            // Create HTTP request
            HttpRequest httpRequest = HttpRequest.newBuilder()
                .uri(URI.create("https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateText?key=" + apiKey))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString("""
                    {"prompt": {"text": "%s"}}
                    """.formatted(prompt)))
                .build();

            // Send HTTP request
            HttpClient client = HttpClient.newHttpClient();
            HttpResponse<String> response = client.send(httpRequest, HttpResponse.BodyHandlers.ofString());

            // Parse Gemini API response
            ObjectMapper mapper = new ObjectMapper();
            JsonNode node = mapper.readTree(response.body());

            // Safely extract suggestion text
            String text = node.path("candidates").get(0).path("content")
                    .path("parts").get(0).path("text").asText("No suggestion");

            // Build structured CompletionResponse
            CompletionResponse cr = new CompletionResponse();
            cr.setSuggestions(List.of(
                new CompletionResponse.Suggestion(
                    "AI Suggestion",
                    text,
                    "Generated by Gemini API"
                )
            ));

            return cr;

        } catch (Exception e) {
            // Fallback in case of any exception
            CompletionResponse fallback = new CompletionResponse();
            fallback.setSuggestions(List.of(
                new CompletionResponse.Suggestion(
                    "Error",
                    "Gemini API call failed.",
                    e.getMessage()
                )
            ));
            return fallback;
        }
    }
}